sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt install -y libgmp-dev
script:
  - git clone https://github.com/herumi/cybozulib.git
  - git clone https://github.com/herumi/xbyak.git
  - git clone https://github.com/herumi/mcl.git
  - git clone https://github.com/herumi/bls.git
  - cd bls
  - make UNIT=4 test
  - make UNIT=4 run_go
  - make clean
  - make UNIT=6 test
  - make UNIT=6 run_go
